global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nethermind'
    static_configs:
      - targets: ['nethermind:8545']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'lighthouse'
    static_configs:
      - targets: ['lighthouse:5052']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'juno'
    static_configs:
      - targets: ['juno:6060']
    metrics_path: '/metrics'
    scrape_interval: 30s
